### PR TITLE
Add debian buster and debian bullseye to CI tests

### PR DESCRIPTION
**Pull request by rw1nkler**
This PR adds tests on debian buster and debian bullseye to the CI

### CODE REVIEW

**Review by acomodi — CHANGES_REQUESTED** [review]
I think that we should only have the buster debian release.

Looking at the bullseye roadmap ([link](https://wiki.debian.org/DebianBullseye)) The release is still under testing until 2021-03-12. I believe that we should only have enabled tests on OSes that are fully supported, even though they turn out to be green on CI (to avoid issues we have seen with the [Ubuntu eoan release](https://github.com/SymbiFlow/symbiflow-examples/pull/91))

**Comment by rw1nkler** [comment]
> Looking at the bullseye roadmap (link) The release is still under testing until 2021-03-12. I believe that we should only have enabled tests on OSes that are fully supported, even though they turn out to be green on CI (to avoid issues we have seen with the Ubuntu eoan release)

That is a good point. I removed the bullseye release

**Review by acomodi — APPROVED** [review]
LGTM

**Comment by mithro** [comment]
FWIW - I'm would like to have debian `stable`, `testing` and `unstable` in the CI system.

**Pull request merged**
