### PR TITLE
Remove `file:` from top level conda env

### PR DESCRIPTION
**Pull request by kgugala**
Signed-off-by: Karol Gugala <kgugala@antmicro.com>

### CODE REVIEW

**Comment by mithro** [comment]
Shouldn't something in the CI have been failing before this change?

**Comment by kgugala** [comment]
> Shouldn't something in the CI have been failing before this change?

Good point. I looked through the docs and it doesn't seem we use this file. Looks like leftover from the times before we added QL examples.

**Comment by kgugala** [comment]
We should probably remove it, instead of fixing it.

**Comment by tmichalak** [comment]
Suprseded by #176. Closing.

**Pull request closed without merging**
