### PR TITLE
Rework in-docker tests so they handle comments in scripts

### LINKED ISSUE #65: None of the XC7 tests are running ... easy fix
Cause is that there is a comment included in the prepare environment snippet

`# adding symbiflow toolchain binaries to PATH`

Got rid of the comment and the tests run ... all pass except for the xc7-litex which i am working on and will report separately

### PR DESCRIPTION
**Pull request by kgugala**
fixes #65

### CODE REVIEW

**Comment by mithro** [comment]
@kgugala - I'm okay with this temporary fix, however the `tuttest` tool should understand how comments work?

**Comment by mgielda** [comment]
Well, the original idea for `tuttest` was not to be language specific and not really provide some of the functionality that you had since requested (which are bash-specific). It's the --single-command option which introduced the bug, but to fix it properly we'd need to make tuttest understand comments in various languages. Bash as such is of course easy to fix, so I think we'll just make this fix in single-command since it's kinda bash-specific anyhow.

**Comment by mithro** [comment]
@mgielda -- Well, shouldn't bash understand that `#` is a comment and just execute nothing?

**Comment by mithro** [comment]
I have forgotten why we needed `--single-command`? I wonder if `--single-command` should actually be generating a script file which it then executes?

**Comment by pgielda** [comment]
I actually think this is not acceptable to merge and we have to fix the underlying issue.

**Comment by pgielda** [comment]
@kgugala  can you apply the approach #68 here instead?

**Comment by kgugala** [comment]
> @kgugala can you apply the approach #68 here instead?

done

**Comment by pgielda** [comment]
Ok, now we have a *real* CI feedback. It seems we have two problems:

1) on old OSes seems that LiteX fails
2) we hit 50min timeout of Travis

I would suggest merging this and open separate issue for (1) -- probably in LiteX using ubuntu:trusty fail as an example.
As for (2) I would suggest temporarily not test the longest test in tuttest (LiteX? Linux/LiteX?). Long term we would have to migrate from Travis, but I know its not trivial because of storage limitations of Github Actions and we need a short term solution.

**Pull request merged**
