### PR TITLE
A few minor clarifications on running examples

### PR DESCRIPTION
**Pull request by WhiteNinjaZ**
I am currently working as a research assistant at Brigham Young University and I have been assigned to work on improving and adding to the documentation within symbiflow-examples, as well as coordinating with other companies to help drive traffic from FPGA design sites to your repository.
In this pull request, I have made a few minor changes to the documentation that I think would have been helpful to me as I worked through the examples.

I look forward to working with you and am excited to play a role in improving this project.

### CODE REVIEW

**Comment by mithro** [comment]
Hi,

Thank you for sending the pull request! It's awesome to see you contributing to this project. However, before I can look at this request you need to add [DCO sign-off](https://developercertificate.org/) to commits in this repository.

We require [DCO sign-off](https://developercertificate.org/) for **all** commits to this repository (including all authors). Please see the [following URL](https://github.com/probot/dco#how-it-works) to see more information and BeeWare also have a [Beginners guide to DCOs](https://pybee.org/contributing/how/dco/).

You can use `git commit --amend --signoff` and then a `git push --force` to add the signoff. You can also use `git rebase --signoff`.

Thanks!

**Review by acomodi — CHANGES_REQUESTED** [review]
Hi, the changes to the READMEs affect the commands executed when running CI by [tuttest](https://github.com/antmicro/tuttest).

For instance, the `enter-dir-xc7` snippet is added prior to running the example build https://github.com/SymbiFlow/symbiflow-examples/blob/043e59355f177855eb138b84e418fde5a23d307d/.github/scripts/build-examples.sh#L57.

Maybe, instead of changing/adding the snippets, it might be worth just adding something like: "From the xc7 directory, run:"

The correct location to look for running and building the examples is [here](https://symbiflow-examples.readthedocs.io/en/latest/building-examples.html)

**Comment by WhiteNinjaZ** [comment]
> Hi,
> 
> Thank you for sending the pull request! It's awesome to see you contributing to this project. However, before I can look at this request you need to add [DCO sign-off](https://developercertificate.org/) to commits in this repository.
> 
> We require [DCO sign-off](https://developercertificate.org/) for **all** commits to this repository (including all authors). Please see the [following URL](https://github.com/probot/dco#how-it-works) to see more information and BeeWare also have a [Beginners guide to DCOs](https://pybee.org/contributing/how/dco/).
> 
> You can use `git commit --amend --signoff` and then a `git push --force` to add the signoff. You can also use `git rebase --signoff`.
> 
> Thanks!

Ok, I added the sign off sheet.

**Comment by nelsobe** [comment]
@WhiteNinjaZ  - looks good to me.  I think it is ready for review by @acomodi ...

**Pull request closed without merging**
