### PR TITLE
Add zynq counter test

### PR DESCRIPTION
**Pull request by acomodi**
This builds on top of https://github.com/SymbiFlow/symbiflow-examples/pull/83 and adds support for the counter test on the zynq.

The design uses the PS7, and based on EMIO pins set/cleared by the PS7, the counter behaves differently.

In addition, this PR moves the constraints to use the XDC format instead of PCF+SDC

### CODE REVIEW

**Review by mithro — APPROVED** [review]
Generally LGTM, assuming you rebase and the non-related changes go away.

**Review by mithro — APPROVED** [review]
LGTM

**Comment by acomodi** [comment]
@mithro I believe we can wait for https://github.com/SymbiFlow/symbiflow-examples/pull/88 to get merged.

Once that is merged, I can also push the tutorial on how to use and program the zynq with this test.

**Comment by rw1nkler** [comment]
Please rebase the PR to enable documentation tests in the CI (building on RTD)

**Pull request merged**
