### PR TITLE
Add nexys video counter target

### PR DESCRIPTION
**Pull request by andrewb1999**
Adds nexys video counter target and updates docs as requested in #63 

Supersedes #79 

Tested on hardware and functions properly.

### CODE REVIEW

**Comment by andrewb1999** [comment]
Okay I guess the issue here is still the same with running out of memory on github actions.  Not sure what the proper next step should be, but it would be good to see nexys video support here.

**Comment by pgielda** [comment]
We are working on custom GA runners that will have more memory.

**Comment by kgugala** [comment]
@andrewb1999 custom runnners are now merged (along with basic nexys_video counter examole). Can you rebase this PR (and check if it's still needed) ?

**Comment by andrewb1999** [comment]
@kgugala Looks like this pr is no longer required.  Good to see nexys_video support merged!

**Pull request closed without merging**
