### PR TITLE
README: Fixing VTR version

### PR DESCRIPTION
**Pull request by acomodi**
Signed-off-by: Alessandro Comodi <acomodi@antmicro.com>

### CODE REVIEW

**Comment by mithro** [comment]
Merge if green?

**Comment by pgielda** [comment]
It would be great to finish the discussion on naming... Now we have symbiflow-vtr that works for xc7 but not for eos3. So I think the package name is still too vague.

**Comment by mithro** [comment]
@pgielda -- Any idea why it doesn't work for the EOS S3 -- I would have thought it should....

**Comment by pgielda** [comment]
Good question, I see no obvious reason. I will investigate this once I have a moment.

**Comment by mithro** [comment]
Is still pull request still needed? I'm going to close it for now, reopen if the change makes sense and you rebase it.

**Pull request closed without merging**
