### PR TITLE
Document the prerequisites on Fedora, and test in CI

### PR DESCRIPTION
**Pull request by umarcor**
As per #30, this PR add 'Fedora latest' to the list of OS used in CI.

### CODE REVIEW

**Comment by pgielda** [comment]
I would probably use "fedora:35" instead of latest (its the same thing but won't "suddenly" break once the version changes on dockerhub). And potentially check "fedora:36" (unstable).

Btw - why are we suddenly adding "git" here? Does fedora fail without installing git?

**Comment by umarcor** [comment]
> I would probably use "fedora:35" instead of latest (its the same thing but won't "suddenly" break once the version changes on dockerhub). And potentially check "fedora:36" (unstable).

Ok. I will update.

> Btw - why are we suddenly adding "git" here? Does fedora fail without installing git?

On the one hand, we are already installing git later in each job, because the prerequisites in the docs include git. Therefore, this is just doing it before.

On the other hand, `actions/checkout` will fall back to the GitHub API if `git` is not found. Currently, this repo uses "Container jobs", which means that all the steps of the job are executed inside the container. Therefore, if `git` is not found, the Action uses the API, and that is undesirable because some features such as option `submodules` might not work. See:

> https://github.com/actions/checkout/#whats-new
> Fallback to REST API download
>
> * When Git 2.18 or higher is not in the PATH, the REST API will be used to download the files
> * When using a job container, the container's PATH is used

In fact, the warning/error is not produced when using the self-hosted runners. I found this when I used the default runners in my fork of this repo. I wonder if the Antmicro runner is doing something different in this regard, or whether it's inherited from GitHub's self-hosted runner codebase.

Nonetheless, I am preparing some further enhancements for allowing forks to not require self-hosted runners. For now I think it's ok to just ensure that `actions/checkout` can use git.

**Comment by umarcor** [comment]
Converted to a draft, while Fedora 36 is tested.

**Comment by pgielda** [comment]
I would move the git change to a separate PR / issue and have a separate discussion, and here just focus on adding Fedora(s) to the CI without touching anything else if possible

**Comment by umarcor** [comment]
@pgielda, done! Unfortunately, the litex example is failing on Fedora 36. Shall I mark this PR as ready for review anyway?

**Comment by pgielda** [comment]
Does it consistently fail on fedora:36? If yes I would prefer to not have fedora:36 in the CI until its fixed in LiteX, otherwise we will have a consistently red CI and this will hide other problems that show up.

**Comment by umarcor** [comment]
It seems to fail consistenly. I removed fedora:36 from this PR. so we can merge and deal with that later.

**Pull request merged**
