### PR TITLE
docs: update xc7 arch-def tarball URLs to '*-latest'

### PR DESCRIPTION
**Pull request by umarcor**
Close #83.

Ref #115.

This PR updates the URLs to download latest arch-def packages for xc7 devices. By the way, xc7z020_test is added.

/cc @mithro

### CODE REVIEW

**Comment by mithro** [comment]
I think we want to continue to used fixed versions which are known to work (as have been tested on CI). The versions *should* be automatically updated to the latest version via a bot....

**Comment by mithro** [comment]
I /think/ an even better solution would be for the tarballs to be distributed via the package management system and could be updated like any other part of the system.

**Comment by mithro** [comment]
I think there was the idea of a "symbiflow-data-manager" tool (https://github.com/SymbiFlow/symbiflow-tools-data-manager) at some point too?

**Comment by mithro** [comment]
Unrelated - why are you converting from `wget` to `curl`? That seems like an unrelated change here?

**Comment by umarcor** [comment]
> Unrelated - why are you converting from `wget` to `curl`? That seems like an unrelated change here?

At some point I looked in #83 and I saw that both were used, and choosing one was suggested. I did not actually check which was used more. Since most of the commands are piping the output, `curl` felt more natural.

Anyway, if the purpose is to have a bot and use pinned versions, I guess we can close both this and #83.

**Comment by mithro** [comment]
BTW -- Being consistent about using `curl` or `wget` seems like a good change on it's own, I recommend you submit that separately.

**Comment by umarcor** [comment]
It's consistent already:

```
/t/symbiflow/symbiflow-examples# grep -lr ./ -e curl

/t/symbiflow/symbiflow-examples# grep -lr ./ -e wget
./.github/scripts/generate_matrices.py
./.github/scripts/install-toolchain.sh
./.github/workflows/sphinx-tuttest.yml
./docs/getting-symbiflow.rst
./docs/running-examples.rst
./scripts/make/conda.mk
./xc7/linux_litex_demo/buildroot/rootfs.cpio
```

The inconsistency was introduced by me during some intermediate stage of this PR.

**Pull request closed without merging**
