### PR TITLE
ci: add non-preemptible exceptions

### PR DESCRIPTION
**Pull request by kgugala**
Signed-off-by: Adam Olech <aolech@antmicro.com>

### CODE REVIEW

**Review by mithro — COMMENTED** [review]
Can we make everything non-preemptible by default? I think we do **not** want anything to be preemptible.

**Comment by pgielda** [comment]
We're testing the feature in custom runners of being able to do it selectively as well. In the end its just a setting so if it keeps failing we can turn it off completely.

**Comment by mithro** [comment]
> We're testing the feature in custom runners of being able to do it selectively as well. In the end its just a setting so if it keeps failing we can turn it off completely.

What I'm saying is that, we should start with **non-preemptible as the default** and then you can work on adding a setting to selectively turn on preemptible functionality where it makes sense (although I'm not sure it ever makes sense on repos I'm supplying resources too?).

**Comment by kgugala** [comment]
seems to be working fine with non-preemptible machines

**Review by mithro — COMMENTED** [review]
LGTM

**Pull request merged**
